services:
  postgres_database:
    image: postgres:17.2-alpine3.21
    container_name: postgres_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_pessoas
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - backend-network

  backend-api:
    container_name: backend-api
    image: backend-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres_database:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local